services:
  frontend:
    build: ./frontend
    command: npx expo start --web --port 19006
    ports:
      - "19006:19006"
      - "19007:19007"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - localstack

  backend-watch:
    build: ./backend
    command: npm run watch
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    profiles:
      - dev

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb,apigateway,s3
      - EDGE_PORT=4566
    ports:
      - "4566:4566"
    volumes:
      - "./backend/localstack:/etc/localstack/init/ready.d"
