service: naosu-park-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  environment:
    DYNAMO_ENDPOINT: http://localstack:4566
    AWS_REGION: us-east-1

plugins:
  - serverless-localstack
  - serverless-offline

custom:
  localstack:
    stages:
      - local
    host: http://localstack
    edgePort: 4566
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0

functions:
  getGames:
    handler: src/handlers/games.getGames
    events:
      - http:
          path: games
          method: get

  postScore:
    handler: src/handlers/score.postScore
    events:
      - http:
          path: score
          method: post

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    ScoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: scores
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: game_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: game_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
